name: REALY
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - scikit-sparse=0.4.6
  - scipy=1.7.3
  - pip:
    - opencv-python==4.6.0.66
    - pandas==1.3.5
    - rtree==1.0.0
    - scikit-learn==1.0.2
    - tqdm==4.64.0
    - trimesh==3.12.7
